In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Functions ##

In [2]:
def spread(values): 
    # spread takes in an array, a set of values
    # finds the maximum value and the minimum
    # and finds the difference between the max and min
    return max(values) - min(values)

In [3]:
ages = make_array(18, 20, 22, 32)

In [4]:
spread(ages) # 32 - 18 = 14

14

In [5]:
def triple(x):
    # takes in an int, float, array, string
    # and multiples by 3
    # returns that value
    return 3 * x

In [7]:
triple(3) # 3 * 3 = 9 

9

In [8]:
num = 4

In [9]:
triple(num) # triple (4) = 3 * 4 = 12

12

In [10]:
triple(num * 5) # triple( 4 * 5) = triple(20) = 3 * 20 = 60

60

### Note About Scopes

In [ ]:
x

In [ ]:
x = 5

In [ ]:
triple(2 * x)

In [ ]:
x

### Type Agnostic

In [11]:
triple('ha')

'hahaha'

In [12]:
'ha'*3

'hahaha'

In [13]:
triple(np.arange(4))
# np.arange(4) = (0, 1, 2, 3)
# (0,1,2,3) * 3 = (0, 3, 6, 9)

array([0, 3, 6, 9])

### Discussion Question

In [14]:
def percentage_of_total(s):
    'percentage_of_total takes in an array
    'finds the proportion of each element, using the sum of total array
    ' converts to percentage
    'returns array, with each element rounded to two decimal places
    return np.round(s / sum(s) * 100, 2)

In [18]:
s = make_array(10, 11) # our input should be a collection of things
# for example, an array
# does not want a single value: float, int

In [20]:
s/sum(s) # proportion

array([0.47619048, 0.52380952])

In [21]:
s/sum(s) * 100 # percentages

array([47.61904762, 52.38095238])

In [22]:
np.round(s / sum(s) * 100, 2)

array([47.62, 52.38])

### Multiple Arguments

$ h^2 = x^2 + y^2 \hspace{20 pt} => \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $

In [23]:
def hypotenuse(x,y):
    hypot_squared = (x ** 2 + y ** 2) # x^2 + y ^2
    return hypot_squared ** 0.5 # or np.sqrt(x**2 + y **2)

In [24]:
hypotenuse(9, 12)

15.0

In [25]:
np.sqrt(9**2 + 12**2)

15.0

In [26]:
help(np.sqrt)

Help on ufunc:

sqrt = <ufunc 'sqrt'>
    sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Return the non-negative square-root of an array, element-wise.
    
    Parameters
    ----------
    x : array_like
        The values whose square-roots are required.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is 

In [27]:
hypotenuse(2, 2)

2.8284271247461903

In [28]:
(2**2 + 2**2)**0.5

2.8284271247461903

## Apply ##

In [29]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
ages

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

In [33]:
def cap_at_1980(x):
    'Take in an array of Date of Births'
    'compare the Birth Year with 1980'
    'and return the minimum value'
    return min(x, 1980)

In [34]:
cap_at_1980(1975)

1975

In [35]:
cap_at_1980(1991)

1980

In [37]:
new_birth_years = ages.apply(cap_at_1980, 'Birth Year')

In [48]:
ages = ages.with_column('New Birth Years', new_birth_years)
ages

Person  | Birth Year | New Birth Years | Message
Jim     | 1985       | 1980            | Jim is 37
Pam     | 1988       | 1980            | Pam is 34
Michael | 1967       | 1967            | Michael is 55
Creed   | 1904       | 1904            | Creed is 118

In [46]:
def name_and_age(name, year):
    age = 2022 - year
    return name + ' is ' + str(age)

In [50]:
name_age_array = ages.apply(name_and_age, 'Person', 'New Birth Years')
ages = ages.with_column('Message', name_age_array)
ages = ages.drop('Birth Year')
ages

Person  | New Birth Years | Message
Jim     | 1980            | Jim is 42
Pam     | 1980            | Pam is 42
Michael | 1967            | Michael is 55
Creed   | 1904            | Creed is 118

In [ ]:
# now, can you create a table of names of each person at your table
# and their Birth Year
# your table should have two columns
# first column: Name, second column: Birth Year




In [ ]:
# BONUS: apply the name_and_age function to your table you created above





In [ ]:
# BONUS BONUS: add a third column to the table you created
# with the ages for each person at your table



