In [77]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Comparison ##

In [78]:
3 > 1

True

In [79]:
type(3 > 1)

bool

In [80]:
True

True

In [81]:
true

NameError: name 'true' is not defined

In [ ]:
3 = 3

In [ ]:
3 == 3.0 # checking for equality

In [ ]:
10 != 2 # checking for inequality

In [ ]:
x = 14
y = 3

In [ ]:
x > 15 # 14 > 15 -> False

In [ ]:
12 < x

In [ ]:
x < 20

In [ ]:
12 < x < 20 # 12 < 14 < 20

In [ ]:
10 < x-y < 13
#10 < 14-3 < 13
# 10 < 11 < 13

In [ ]:
x > 13 and y < 3.14159

In [ ]:
x < 13 and y < 3.14159 # need both comparisons to be true
# for the entire conditional statement to be true

In [82]:
x < 13 or y < 3.14159 # just need one to be true
# for the entire conditional statement to be true


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Comparisons with arrays

In [ ]:
pets = make_array('cat', 'cat', 'dog', 'cat', 'dog', 'rabbit')
pets

In [ ]:
pets == 'cat' # checking the entire array for when it's equal to cats
# this should produce an array with boolean values, True or False

In [ ]:
1 + 1 + 0 + 1 + 0 + 0

In [ ]:
sum(make_array(True, True, False, True, False, False))
# sum(make_array(1,    1 ,  0,        1,    0,    0))

In [ ]:
sum(pets == 'dog')
# sum((False, False, True, False, True, False))
# sum(0,           0,    1,    0,     1,     0))

In [ ]:
np.count_nonzero(pets == 'dog')

In [83]:
x = np.arange(20, 31)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [84]:
x > 28

array([False, False, False, False, False, False, False, False, False,
        True,  True])

In [85]:
np.count_nonzero(x > 28)
# np.count_nonzero(array([False, False, False, False, False, False, False, False, False,
#        True,  True])
# np.count_nonzero(array([0, 0, 0, 0,0,0,0,0,0,1,1])


2

## Simulation

Let's play a game: we each roll a die. 

If my number is bigger: you pay me a dollar.

If they're the same: we do nothing.

If your number is bigger: I pay you a dollar.

Steps:
1. Find a way to simulate two dice rolls.
2. Compute how much money we win/lose based on the result.
3. Do steps 1 and 2 10,000 times.

### Conditional Statements

In [86]:
# Work in progress
def one_round(my_roll, your_roll):
    if my_roll > your_roll:
        return 1

In [87]:
one_round(4, 3)

1

In [88]:
one_round_better(2, 6) # nothing returned
# because we didn't consider this scenario


-1

In [89]:
# Final correct version
def one_round_better(my_roll, your_roll):
    if my_roll > your_roll: # say I roll a 6 and you roll a 3
        return 1 # you owe me a dollar
    elif my_roll < your_roll: # say I roll a 3 and you roll a 6
        return -1 # i owe you a dollar
    else: # covers any other scenario
        return 0



In [90]:
one_round_better(1, 1)

0

In [91]:
one_round_better(6, 5)

1

In [92]:
one_round_better(7, -1)

1

In [93]:
# challenge
# can you define a function
# one_round_best
# which makes sure the inputs are found on a six-sided die
# 1, 2, 3, 4, 5, 6

# if you get a number that's not found on a six-sided die
# tell the user to try again

### Random Selection

In [94]:
mornings = make_array('wake up', 'sleep in')

In [95]:
np.random.choice(mornings)

'sleep in'

In [96]:
np.random.choice(mornings)

'sleep in'

In [97]:
np.random.choice(mornings)

'sleep in'

In [98]:
np.random.choice(mornings, 7)

array(['sleep in', 'sleep in', 'sleep in', 'sleep in', 'sleep in',
       'sleep in', 'wake up'], dtype='<U8')

In [99]:
sum(np.random.choice(mornings, 7) == 'wake up')

5

In [100]:
sum(np.random.choice(mornings, 7) == 'sleep in')

3

In [101]:
morning_week = np.random.choice(mornings, 7)
morning_week

array(['wake up', 'wake up', 'wake up', 'wake up', 'wake up', 'sleep in',
       'wake up'], dtype='<U8')

In [102]:
sum(morning_week == 'wake up')

6

In [103]:
sum(morning_week == 'sleep in')

1

In [104]:
die_faces = np.arange(1, 7)

In [105]:
np.random.choice(die_faces)

2

In [107]:
def simulate_one_round():
    my_roll = np.random.choice(die_faces)
    your_roll = np.random.choice(die_faces)
    return one_round_better(my_roll, your_roll)

In [108]:
simulate_one_round()

0

### Appending Arrays

In [109]:
first = np.arange(4)
second = np.arange(10, 17)

In [110]:
np.append(first, 6)

array([0, 1, 2, 3, 6])

In [111]:
first

array([0, 1, 2, 3])

In [112]:
np.append(first, second)

array([ 0,  1,  2,  3, 10, 11, 12, 13, 14, 15, 16])

In [113]:
first

array([0, 1, 2, 3])

In [114]:
second

array([10, 11, 12, 13, 14, 15, 16])

In [115]:
third = np.append(first, second)
third

array([ 0,  1,  2,  3, 10, 11, 12, 13, 14, 15, 16])

### Repeated Betting ###

In [116]:
results = make_array() # initialize an empty array

In [126]:
results = np.append(results, simulate_one_round())
results

array([-1., -1.,  0.,  0.,  0., -1.,  1., -1.,  1., -1.])

## `For` Statements

In [128]:
for pet in make_array('cat', 'dog', 'rabbit'):
    # loop = 1, pet = array.item(0) = 'cat'
    # loop = 2, pet = array.item(1) = 'dog'
    # loop = 3, pet = array.item(2) = 'rabbit'
    print('I love my ' + pet)

I love my cat
I love my dog
I love my rabbit


In [127]:
pet = make_array('cat', 'dog', 'rabbit').item(0)
print('I love my ' + pet)

pet = make_array('cat', 'dog', 'rabbit').item(1)
print('I love my ' + pet)

pet = make_array('cat', 'dog', 'rabbit').item(2)
print('I love my ' + pet)

I love my cat
I love my dog
I love my rabbit


In [132]:
game_outcomes = make_array() # initialize an array to collect stuff later
# let's simulate 5 games 
game_outcomes = np.append(game_outcomes, simulate_one_round())
game_outcomes = np.append(game_outcomes, simulate_one_round())
game_outcomes = np.append(game_outcomes, simulate_one_round())
game_outcomes = np.append(game_outcomes, simulate_one_round())
game_outcomes = np.append(game_outcomes, simulate_one_round())

game_outcomes

array([ 0.,  0.,  1.,  0., -1.])

In [134]:
game_outcomes = make_array()

# run line 4 five times
# for i in array:
    # body of my for loop
    # instructions to repeat however many times
    
for i in make_array(1,2,3,4,5):
    # array has 5 things in it
    # so this for loop is going to run 5 times
    # loop = 1, i = array.item(0) = 1
    # loop = 2, i = array.item(1) = 2
    # loop = 3, i = array.item(2) = 3
    # loop = 4, i = array.item(3) = 4
    # loop = 5, i = array.item(4) = 5
    game_outcomes = np.append(game_outcomes, simulate_one_round())
game_outcomes

array([ 1., -1.,  1.,  1.,  0.])

In [ ]:
game_outcomes = make_array()

# let's simulate 10,000 games




In [ ]:
len(game_outcomes)

In [ ]:
results = Table().with_column('My winnings', game_outcomes)

In [ ]:
results

In [ ]:
results.group('My winnings').barh('My winnings')

In [ ]:
# Bonus question: This simulation is relatively simple. 
# Can you find a way to run it without using a for loop?




### Another example: simulating heads in 100 coin tosses

In [ ]:
coin = make_array('heads', 'tails')

In [ ]:
sum(np.random.choice(coin, 100) == 'heads')

In [ ]:
# Simulate one outcome

def num_heads():
...

In [ ]:
# Decide how many times you want to repeat the experiment

repetitions = 10000

In [ ]:
# Simulate that many outcomes

...


...
...
...

In [ ]:
heads = Table().with_column('Heads', outcomes)
heads.hist(bins = np.arange(29.5, 70.6))

## Optional: Advanced `where` ##

In [ ]:
ages = make_array(16, 22, 18, 15, 19, 15, 16, 21)
age = Table().with_column('Age', ages)

In [ ]:
age

In [ ]:
age.where('Age', are.above_or_equal_to(18))

In [ ]:
voter = ages >= 18

In [ ]:
voter

In [ ]:
age.where(voter)

In [ ]:
is_voter = are.above_or_equal_to(18)

In [ ]:
type(is_voter)

In [ ]:
is_voter(22)

In [ ]:
is_voter(3)

In [ ]:
age.apply(is_voter, 'Age')

In [ ]:
ages >= 18

In [ ]:
voter

In [ ]:
def my_voter_function(x):
...

In [ ]:
age.where('Age', are.above_or_equal_to(18))

In [ ]:
age.where(voter)

In [ ]:
age.where('Age', my_voter_function)